/* Global parameter file */
#define GLOBALPAR_M 1.0
#define GLOBALPAR_astar 0.9
#define GLOBALPAR_mu_inner 0.00001
#define GLOBALPAR_mu_outer 0.00001
#define GLOBALPAR_n_time 50
#define GLOBALPAR_sm_axis_inner 50
#define GLOBALPAR_sm_axis_outer 300
#define GLOBALPAR_N_sys 50
#define GLOBALPAR_N_res 1
#define GLOBALPAR_nl_res 4
#define GLOBALPAR_N_min_Fourier -5
#define GLOBALPAR_N_max_Fourier 5
#define GLOBALPAR_t0 1.0
#define GLOBALPAR_nl_self 1
#define GLOBALPAR_nmax 1
#define GLOBALPAR_kmax 1
#define GLOBALPAR_mmax 1
#define GLOBALPAR_chunk_size 4
